spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: r1
              uri: lb://CONFERENCE-SERVICE
              predicates:
                - Path=/api/conferences/**
            - id: r2
              uri : lb://KEYNOTE-SERVICE
              predicates:
                - Path=/api/keynotes/**
